import type { Persona, WatchCase } from "./types";

export const personas: Persona[] = [
  { id: 1, name: "Priya Nair", initials: "PN", role: "CASE_OWNER", division: "PNC" },
  { id: 2, name: "Marcus Reed", initials: "MR", role: "APPROVER", division: "PNC" },
  { id: 3, name: "Elena Voss", initials: "EV", role: "CASE_OWNER", division: "GWMA" },
  { id: 4, name: "Daniel Cho", initials: "DC", role: "APPROVER", division: "GWMA" },
  { id: 5, name: "Aisha Grant", initials: "AG", role: "CASE_OWNER", division: "GWMSI" },
  { id: 6, name: "Thomas Bell", initials: "TB", role: "APPROVER", division: "GWMSI" },
  { id: 7, name: "Vikram Shah", initials: "VS", role: "CASE_OWNER", division: "IB" },
  { id: 8, name: "Sofia Marin", initials: "SM", role: "APPROVER", division: "IB" },
  { id: 9, name: "Jordan Lee", initials: "JL", role: "ADMIN" },
];

export const cases: WatchCase[] = [
  {
    id: 101,
    reference: "CWL-2026-0142",
    borrower: "Aperture Retail Group",
    division: "PNC",
    sector: "Consumer discretionary",
    exposure: 48200000,
    riskRating: "6 - Special mention",
    previousRating: "5 - Acceptable",
    status: "ACTIVE",
    owner: "Priya Nair",
    approver: "Marcus Reed",
    nextReview: "Jun 18",
    daysOnWatchlist: 94,
    triggers: ["Covenant breach", "Liquidity pressure"],
    summary: "Two consecutive quarters of margin compression and delayed inventory conversion.",
    actionProgress: 68,
    openActions: 3,
    overdueActions: 1,
    lastActivity: "Review evidence added 2h ago",
  },
  {
    id: 102,
    reference: "CWL-2026-0138",
    borrower: "Northstar Renewables",
    division: "IB",
    sector: "Energy",
    exposure: 126500000,
    riskRating: "7 - Substandard",
    previousRating: "6 - Special mention",
    status: "PENDING_APPROVAL",
    owner: "Vikram Shah",
    approver: "Sofia Marin",
    nextReview: "Jun 15",
    daysOnWatchlist: 61,
    triggers: ["Project delay", "Sponsor support"],
    summary: "Construction completion moved by five months; contingency facility is 73% utilized.",
    actionProgress: 44,
    openActions: 5,
    overdueActions: 2,
    lastActivity: "Monthly review submitted yesterday",
  },
  {
    id: 103,
    reference: "CWL-2026-0111",
    borrower: "Morrow Health Systems",
    division: "GWMSI",
    sector: "Healthcare",
    exposure: 73800000,
    riskRating: "6 - Special mention",
    previousRating: "6 - Special mention",
    status: "ACTIVE",
    owner: "Aisha Grant",
    approver: "Thomas Bell",
    nextReview: "Jun 21",
    daysOnWatchlist: 147,
    triggers: ["Receivables aging", "Management change"],
    summary: "Receivables above 90 days remain elevated while the new CFO resets collections.",
    actionProgress: 81,
    openActions: 2,
    overdueActions: 0,
    lastActivity: "Action closed 3h ago",
  },
  {
    id: 104,
    reference: "CWL-2026-0096",
    borrower: "Canopy Hospitality Partners",
    division: "GWMA",
    sector: "Real estate",
    exposure: 31900000,
    riskRating: "7 - Substandard",
    previousRating: "6 - Special mention",
    status: "REMOVAL_PENDING",
    owner: "Elena Voss",
    approver: "Daniel Cho",
    nextReview: "Jun 12",
    daysOnWatchlist: 213,
    triggers: ["Debt service coverage", "Occupancy"],
    summary: "Occupancy and debt service coverage have remained above exit thresholds for 90 days.",
    actionProgress: 100,
    openActions: 0,
    overdueActions: 0,
    lastActivity: "Removal requested 4h ago",
  },
  {
    id: 105,
    reference: "CWL-2026-0153",
    borrower: "BluePeak Components",
    division: "PNC",
    sector: "Industrials",
    exposure: 26700000,
    riskRating: "5 - Acceptable",
    previousRating: "5 - Acceptable",
    status: "DRAFT",
    owner: "Priya Nair",
    approver: "Marcus Reed",
    nextReview: "Jul 01",
    daysOnWatchlist: 0,
    triggers: ["Customer concentration"],
    summary: "Largest customer announced a supplier consolidation review.",
    actionProgress: 10,
    openActions: 2,
    overdueActions: 0,
    lastActivity: "Draft saved 25m ago",
  },
];

export const formatMoney = (value: number) =>
  new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    notation: "compact",
    maximumFractionDigits: 1,
  }).format(value);
